// This file was generated by stsc. Please do not edit by hand.
export const aFg = '#fff';

export const bBg = 'rgba(119, 134, 153, 0.59)';

export const aClass = {
  fontFamily: 'Roboto',
  fontSize: '14px',
  fontWeight: '500',
  lineHeight: '2.57',
  color: aFg
};

export const bClass = {
  fontFamily: 'Roboto',
  fontSize: '14px',
  fontWeight: '500',
  lineHeight: '2.57',
  color: bBg
};